Refactor/creation-flow
geyserfund/geyser-app pull request #1258
Opened 2023-12-17 17:42 UTC by sajald77

resolves GEY-5638

2024-01-05 09:17 UTC, travishoglund requested changes
Fantastic work on this - I added some comments, but it looks really good

2024-01-05 14:54 UTC, sajald77 commented on src/components/ui/TextArea.tsx
> +      borderColor: `${colors.primary[500]} !important`,
Yes, I got that, and yes it is intended. I checked all the places it was used, and was surprised why it is not standard like the designs.

2024-01-05 14:54 UTC, sajald77 commented on src/components/ui/TextInputBox.tsx
> +            _focus={{ borderColor: `primary.500`, boxShadow: 'none' }}
same as above

2024-01-05 14:54 UTC, sajald77 commented on src/pages/projectCreate/ProjectCreateStart.tsx
> +          <Box w="100%"></Box>
I think that needs removing, nice catch.

2024-01-10 08:30 UTC, travishoglund approved these changes

2024-01-10 14:28 UTC, merged